name: Pull Request
on:
  pull_request: {}
  push:
    branches:
      - main

permissions: {}

jobs:
  bazel_test:
    name: Bazel test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel

      - name: Test
        shell: bash
        run: bazel test --config ci //...
